title: "Adriansson Advokatbyrå"
description: "Adriansson Advokatbyrå AB"
phone: "+4618341400"
phone_display: "+46 (0)18 34-14-00"
email: "info@abyra.se"
baseurl: ""
collections:
- medarbetare
navigation:
- text: Hem
  url: /
- text: Verksamhetsområden
  url: /verksamhetsomraden/
- text: Aktuellt
  url: /aktuellt/
- text: Medarbetare
  url: /medarbetare/
- text: Kontakt
  url: /kontakt/
exclude: [
    "node_modules",
    "Gemfile",
    "Gemfile.lock",
    "package.json",
    "CNAME",
    "README.md",
    "LICENSE",
    ".gitignore",
    ".vscode",
    "browserlist"
]

